# config.py - System thresholds and runtime parameters

DEFAULT_EAR_THRESHOLD = 0.2
DROWSY_CLOSED_DURATION = 2.0

PERCLOS_WINDOW = 60.0
PERCLOS_THRESHOLD = 0.4
PERCLOS_MIN_OBSERVATION_TIME = 10.0

CNN_CLOSED_CONFIDENCE_THRESHOLD = 0.88
EAR_SMOOTHING_ALPHA = 0.25

BLINK_RATE_WINDOW = 10
BLINK_RATE_THRESHOLD = 10
BLINK_DEBOUNCE_FRAMES = 2
BLINK_MIN_DURATION = 0.04
BLINK_MAX_DURATION = 0.80
BLINK_REFRACTORY = 0.05
BLINK_EAR_MARGIN = 0.015

CALIBRATION_DURATION = 5.0
CALIBRATION_RATIO = 0.6
FACE_LOSS_THRESHOLD = 2.0
